### ISSUE TITLE
Issue in angular-formio-pdf when dynamically render the html tags

### ISSUE THREAD

**Issue by Sarubala** [rssaranece94/angular-formio-pdf#2]
While using html tags in components content, <br> and <b> are rendering as text instead of html tags. But some tags like <center> are working fine. Please help me to solve this.

**Comment by rssaranece94** [comment]
Hi, can you share sample component data or share the screenshots of the input and current output and how you requested to change, let me look further thanks.

**Comment by Sarubala** [comment]
Hi Saran, Thank you so much for the reply. Here I will attach sample
component data and output screen:

Code:
"components": [
          {
            "label": "<b> Name </b>",
            "allowMultipleMasks": false,
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "name",
            "properties": {},
            "tags": []
          },
          {
            "label": "Columns",
            "columns": [
              {
                "components": [
                  {
                    "label": "Date Of Birth </br>",
                    "allowMultipleMasks": false,
                    "showWordCount": false,
                    "showCharCount": false,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "textfield",
                    "input": true,
                    "key": "dob",
                    "properties": {},
                    "tags": []
                  }
                ],
                "width": 6,
                "offset": 0,
                "push": 0,
                "pull": 0,
                "type": "column",
                "hideOnChildrenHidden": false,
                "input": true,
                "key": "",
                "tableView": true,
                "label": ""
              },
              {
                "components": [
                  {
                    "label": "Qualification",
                    "allowMultipleMasks": false,
                    "showWordCount": false,
                    "showCharCount": false,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "textfield",
                    "input": true,
                    "key": "qualification",
                    "properties": {},
                    "tags": []
                  }
                ],
                "width": 6,
                "offset": 0,
                "push": 0,
                "pull": 0,
                "type": "column",
                "hideOnChildrenHidden": false,
                "input": true,
                "key": "",
                "tableView": true,
                "label": ""
              }
            ],
            "mask": false,
            "tableView": false,
            "alwaysEnabled": false,
            "type": "columns",
            "input": false,
            "key": "columns"
          },
          {
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "table",
            "input": false,
            "key": "table",
            "label": "",
            "rows": [
              [
                {
                  "components": [
                    {
                      "label": "HTML",
                      "className": "",
                      "attrs": [],
                      "content": "Sample table header",
                      "refreshOnChange": false,
                      "mask": false,
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "htmlelement",
                      "input": false,
                      "key": "html"
                    }
                  ]
                },
                {
                  "components": [
                    {
                      "label": "HTML",
                      "className": "",
                      "attrs": [],
                      "content": "Sample header",
                      "refreshOnChange": false,
                      "mask": false,
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "htmlelement",
                      "input": false,
                      "key": "html2"
                    }
                  ]
                },
                {
                  "components": [
                    {
                      "label": "HTML",
                      "className": "",
                      "attrs": [],
                      "content": "Sample header",
                      "refreshOnChange": false,
                      "mask": false,
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "htmlelement",
                      "input": false,
                      "key": "html3"
                    }
                  ]
                }
              ],
              [
                {
                  "components": [
                    {
                      "label": "Email",
                      "hideLabel": true,
                      "placeholder": "Email",
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "email",
                      "input": true,
                      "key": "email"
                    }
                  ]
                },
                {
                  "components": [
                    {
                      "label": "url",
                      "hideLabel": true,
                      "placeholder": "Url",
                      "allowMultipleMasks": false,
                      "showWordCount": false,
                      "showCharCount": false,
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "url",
                      "input": true,
                      "key": "url2"
                    }
                  ]
                },
                {
                  "components": [
                    {
                      "label": "Radio",
                      "optionsLabelPosition": "right",
                      "values": [
                        {
                          "label": "one",
                          "value": "one",
                          "shortcut": ""
                        },
                        {
                          "label": "two",
                          "value": "two",
                          "shortcut": ""
                        }
                      ],
                      "inline": false,
                      "mask": false,
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "radio",
                      "input": true,
                      "key": "radio"
                    }
                  ]
                }
              ],
              [
                {
                  "components": [
                    {
                      "label": "Date / Time",
                      "hideLabel": true,
                      "format": "DD-MM-YYYY",
                      "mask": false,
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "datetime",
                      "input": true,
                      "key": "dateTime",
                      "suffix": true,
                      "widget": {
                        "type": "calendar",
                        "displayInTimezone": "viewer",
                        "language": "en",
                        "useLocaleSettings": false,
                        "allowInput": true,
                        "mode": "single",
                        "enableTime": true,
                        "noCalendar": false,
                        "format": "DD-MM-YYYY",
                        "defaultDate": "",
                        "hourIncrement": 1,
                        "minuteIncrement": 1,
                        "time_24hr": false,
                        "minDate": null,
                        "maxDate": null
                      }
                    }
                  ]
                },
                {
                  "components": [
                    {
                      "label": "Select",
                      "hideLabel": true,
                      "mask": false,
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "select",
                      "input": true,
                      "key": "select",
                      "defaultValue": "",
                      "validate": {
                        "customMessage": "",
                        "json": ""
                      },
                      "data": {
                        "values": [
                          {
                            "label": "one",
                            "value": "one"
                          },
                          {
                            "label": "two",
                            "value": "two"
                          }
                        ]
                      },
                      "encrypted": false,
                      "valueProperty": "value"
                    }
                  ]
                },
                {
                  "components": [
                    {
                      "label": "Checkbox",
                      "shortcut": "",
                      "mask": false,
                      "tableView": true,
                      "alwaysEnabled": false,
                      "type": "checkbox",
                      "input": true,
                      "key": "checkbox"
                    }
                  ]
                }
              ]
            ],
            "header": []
          }
        ]


Output:

[image: image.png]

In the above output, I need the name in bold. For that I gave <b> tag
inside the component label for dynamic bind. But here that <b> tag also
comes as above in heading. And also I need a new break line after Date Of
Birth. For that I gave the </br> tag. It also comes as data like in the
above output.

**Comment by rssaranece94** [comment]
@Sarubala labels are already in bold format and spaced properly, then why trying to make it bold and adding break tags again?  Html tags are not supported label & its values.

**Comment by Sarubala** [comment]
Hi Saravana,

I will attach a new set of screenshots for the issue. The output I got was:

[image: image.png]

In the above screenshot the text has to get bold, but here the <b> tag gets
displayed.

I will attach a screenshot for the input that I am using here.

[image: image.png]

In the attached screen there is both <b> tag and <br> tag. But for <br> the
line gets break and started from a new line. But for <b> tag the tag itself
is coming.

Please see this.

Thanks.

Regards,
V. Sarubala
