### ISSUE TITLE
images are not displaying in pdf 

### ISSUE THREAD

**Issue by innoclique** [rssaranece94/angular-formio-pdf#8]
if we add file/images or signature directly they are not rendering in PDF whereas if we add them in table layout then they are rendering.

**Comment by talha48** [comment]
Hi,

I want to show images on form. How it could be ?

**Comment by rssaranece94** [comment]
@innoclique images or any other elements will always be rendered inside any one of these layouts (column, table or panel).

**Comment by rssaranece94** [comment]
@talha48 plz refer #9
