### ISSUE TITLE
How to show images on form?

### ISSUE THREAD

**Issue by talha48** [rssaranece94/angular-formio-pdf#9]
I am using form builder. I have a question how image can be shown on form ?

**Comment by rssaranece94** [comment]
Element object should be defined as below, add base64 image data to src of img. Eg: **img src="{base64}" alt=""** this syntax to be followed with **type:'htmlelement'**.

You can define as signature type and give base64 as input in submission object thanks.

 `{
          label: 'HTML',
          className: '',
          attrs: [],
          content:
            **'<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAsQAAALEBxi1JjQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAJBSURBVEiJndbLi05xGAfwz8yZ120KQ2OQcinCYiZGLETKjlLKJWWwsDI1LmEnuazcGtdY0EyKf4EsZKNGFi6xsJCFjXJLESEWz2/q53jn9b6+9XZ+5/n9nu/3POe5vKfJn+jAQbTgJ57jJj5rDB2Yj3stpY23GI0BPMQinMNZPKmDuIJezMRX/Kp2qMAFLMycrqC9DoGLWJrW/ehoxrREOoyfuIPp6X4fDqVrLczBezxIIq/wBk4l5VzkCNrSega6xasaCbMwiCk4lvgqRDILXMN5DGGBSNKH5FxgrUh0C35UIT+CAziZ1i/zA2fSdW560rElggIrUqRFaS9/8sF0/xd2YnG1jRKu/g85tCbncsmW0YM+TMaeeskLfBcZP477+FLl3FGR7B1YiafJvhGHk39VNGXrdtHFrfgkGm4C7uKW6IW9okp2YUs62z8SeVmgbC9ExQxglIhutijXY+JVbcO7WgK1UBGl24PmZFuO02IUvBA5qYmRIhgmv+TvGdSL1UngmWjIWk1YlfwyOjG+tNeMG6J6rou8DVdXw+RdKYocPaIst4ocNCQyTN6VfpdFV59PkXRmgn2NihRiQHVn5GMyW2eyVTKfPlFFbUlkKjZjf5m8SSQzf/J/keci/4xkDdaLWj8tGqwcTTXyXKQnE5lUFtmOJZnDmVI0tcjLIm2YmGw7sIlI4CDGpY1Kg+RlkRz9Bb7hsZj3r7EMG7BbDMJ6MYRV4r/8EeZhXt7J47FOfFncNsIXQR3YKEbKR5z4DVmgeB++0KQUAAAAAElFTkSuQmCC" alt="">',**
          refreshOnChange: false,
          mask: false,
          style: {
            bold: true,
            margin: [0, 0, 0, 0],
            lineHeight: 1.3,
            fontSize: 14,
            color: '#000',
            alignment: 'center'
          },
          tableView: true,
          alwaysEnabled: false,
          **type: 'htmlelement',**
        ....
}`
